apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      serviceAccountName: web-sa
      containers:
        - name: webserver
          image: 381492257993.dkr.ecr.us-east-1.amazonaws.com/webserver:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
