apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-app
  namespace: argocd
spec:
  destination:
    namespace: webserver
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/BenArtzi4/iac-eks-webserver.git
    targetRevision: main
    path: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensure namespace exists
