name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <AWS_ECR_REPOSITORY>

      - name: Build Docker Image
        run: |
          docker build -t <AWS_ECR_REPOSITORY>:latest ./webserver

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push <AWS_ECR_REPOSITORY>:latest

  update-gitops:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Kubernetes Deployment in Git
        run: |
          sed -i 's|<AWS_ECR_REPOSITORY>:.*|<AWS_ECR_REPOSITORY>:latest|g' kubernetes/deployment.yaml
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "CI Bot"
          git add kubernetes/deployment.yaml
          git commit -m "Update deployment image to latest"
          git push
