name: Build and Push to ECR

on:
  push:
    branches:
      - main

# Add permissions at the top level
permissions:
  contents: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPOSITORY }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY }}:latest ./webserver

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:latest

  update-gitops:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "CI Bot"
          git remote set-url origin https://github.com/${{ github.repository }}
          git config --global credential.helper 'store'

      - name: Update Kubernetes Deployment in Git
        run: |
          sed -i 's|image: .*|image: ${{ secrets.AWS_ECR_REPOSITORY }}:latest|g' kubernetes/deployment.yaml
          git add kubernetes/deployment.yaml
          git diff --quiet kubernetes/deployment.yaml || git commit -m "Update deployment image to latest"
          git push https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} HEAD:main
